apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcua-mapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opcuamapper
  template:
    metadata:
      labels:
        app: opcuamapper
    spec:
      hostNetwork: true
      containers:
      - name: opcua-mapper-container
        image: opcuamapper:v1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kubeedge/
      nodeSelector:
        opcua: "true"
      volumes:
      - name: config-volume
        configMap:
          name: device-profile-config-test
      restartPolicy: Always
