grpc_server:
  socket_path: /etc/kubeedge/kubeedge-v1.17.0.sock
common:
  name: github.com/kubeedge/mqtt-mapper
  version: v1.13.0
  api_version: v1.0.0
  protocol: mqtt
  address: 127.0.0.1
  edgecore_sock: /etc/kubeedge/dmi.sock
