apiVersion: apps/v1
kind: Deployment
metadata:
  name: ble-mapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  ble-mapper
  template:
    metadata:
      labels:
        app:  ble-mapper
    spec:
      hostNetwork: true
      containers:
        - name: ble-mapper-container
          image:  ble-mapper:latest # give your own image of ble mapper
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: config-volume
              mountPath: /opt/kubeedge/
      nodeSelector:
        ble: "true"
      volumes:
        - name: config-volume
          configMap:
            name: device-profile-config-xxxx  # give you own name of configmap
      restartPolicy: Always
