apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: random-instance-01
  labels:
    model: random-01
spec:
  deviceModelRef:
    name: random-01
  protocol:
    customizedProtocol:
      protocolName: virtualProtocol
      configData:
        deviceID: 2
    common:
      com:
        serialPort: '/dev/ttyS0'
        baudRate: 9600
        dataBits: 8
        parity: even
        stopBits: 1
      customizedValues:
        protocolID: 1
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - edge-node
  propertyVisitors:
    - propertyName: random-int
      customizedProtocol:
        protocolName: virtualProtocol
        configData:
          dataType: int
    - propertyName: random-float
      customizedProtocol:
        protocolName: virtualProtocol
        configData:
          dataType: float
status:
  twins:
    - propertyName: random-int
      reported:
        metadata:
          timestamp: '1550049403598'
          type: integer
        value: "100"
      desired:
        metadata:
          timestamp: '1550049403598'
          type: integer
        value: "100"
    - propertyName: random-float
      reported:
        metadata:
          timestamp: '1550049403598'
          type: float
        value: "30"
      desired:
        metadata:
          timestamp: '1550049403598'
          type: float
        value: "30"
