grpc_server:
  socket_path: /tmp/a.sock
common:
  name: mapper-test
  version: v1.0.0
  api_version: v1.0.0
  protocol: modbus
  address: 127.0.0.1
  edgecore_sock: /etc/kubeedge/dmi.sock
dev_init:
  mode: register #register/metaserver/configmap
  configmap: /opt/kubeedge/deviceProfile.json
  metaserver:
    addr: http://10.32.209.110:10550
    namespace: dec-public
