apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: led-instance-01
  labels:
    model: led-model
spec:
  deviceModelRef:
    name: led-model
  protocol:
    customizedProtocol:
      protocolName: GPIO
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - edge-a200-00 #pls give your edge node name
  propertyVisitors:
    - propertyName: red-power-status
      collectCycle: 10000000000     #Mapper 从设备收集数据的频率
      reportCycle: 1000000000     #Mapper 报告数据的频率
      customizedProtocol:
        protocolName: GPIO
        configData:
          pin: 0 #pls give your red light's Pin
    - propertyName: green-power-status
      collectCycle: 10000000000     #Mapper 从设备收集数据的频率
      reportCycle: 1000000000     #Mapper 报告数据的频率
      customizedProtocol:
        protocolName: GPIO
        configData:
          pin: 1 #pls give your green light's Pin
    - propertyName: yellow-power-status
      collectCycle: 10000000000     #Mapper 从设备收集数据的频率
      reportCycle: 1000000000     #Mapper 报告数据的频率
      customizedProtocol:
        protocolName: GPIO
        configData:
          pin: 3 #pls give your yellow light's Pin, pin 2 is not vaild for atlas200dk
    
status:
  twins:
    - propertyName: red-power-status
      reported:
        metadata:
          timestamp: '1550049403598'
          type: string
        value: "OFF"
      desired:
        metadata:
          timestamp: '1550049403598'
          type: string
        value: "OFF"
    - propertyName: green-power-status
      reported:
        metadata:
          timestamp: '1550049403598'
          type: string
        value: "OFF"
      desired:
        metadata:
          timestamp: '1550049403598'
          type: string
        value: "ON"
    - propertyName: yellow-power-status
      reported:
        metadata:
          timestamp: '1550049403598'
          type: string
        value: "OFF"
      desired:
        metadata:
          timestamp: '1550049403598'
          type: string
        value: "OFF"
    
