apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: random-instance-01
  labels:
    model: random-01
spec:
  deviceModelRef:
    name: random-01
  protocol:
    protocolName: virtualProtocol  # in your mapper, this should be replaced by the protocol name your use
    configData:
      deviceID: 2
      serialPort: '/dev/ttyS0'
      baudRate: 9600
      dataBits: 8
      parity: even
      stopBits: 1
      protocolID: 1
  nodeName: edge-node
  properties:
    - name: random-int
      visitors:
        protocolName: virtualProtocol # in your mapper, this should be replaced by the protocol name your use
        configData:
          dataType: int
      reportCycle: 10000000000
      collectCycle: 10000000000
      reportToCloud: true
      pushMethod:
        mqtt:
          address: tcp://192.168.1.73:1883 # replace it by the url of your mqtt client
          topic: random-int
          qos: 0
          retained: false
        dbMethod:
          influxdb2:
            influxdb2ClientConfig:
              url: http://192.168.1.73:8086 # replace it by the url of your influxdb
              org: test-org
              bucket: test-bucket
            influxdb2DataConfig:
              measurement: stat
              tag:
                unit: temperature
              fieldKey: wbctest
    - name: random-float
      visitors:
        protocolName: virtualProtocol
        configData:
          dataType: float
      reportCycle: 10000000000
      collectCycle: 10000000000
      reportToCloud: true
      pushMethod:
        mqtt:
          address: tcp://192.168.1.73:1883
          topic: random-float
          qos: 0
          retained: false
status:
  twins:
    - propertyName: random-int
      reported:
        metadata:
          timestamp: '1550049403598'
          type: integer
        value: "100"
      observedDesired:
        metadata:
          timestamp: '1550049403598'
          type: integer
        value: "100"
    - propertyName: random-float
      reported:
        metadata:
          timestamp: '1550049403598'
          type: float
        value: "30"
      observedDesired:
        metadata:
          timestamp: '1550049403598'
          type: float
        value: "30"
